apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefull
  labels:
    app: state
spec:
  selector:
    matchLabels:
      app: state
  replicas: 4
  template:
    metadata:
      labels:
        name: mysqldatabase
        app: state
    spec:
      containers:
      - name: mysql
        image: tomcat #mysql
        ports:
        - containerPort: 8080 #3306
          protocol: TCP
        #env:
       # - name: MYSQL_ROOT_PASSWORD
        #  value: "1234"
