apiVersion: v1
kind: Pod
metadata:
  name: demopod
  labels:
  app: new-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      Ports:
        - containerPort: 80
          protocol: TCP  