apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  selector: 
    app: new-app
  ports:
    - port: 80
      targetPort: 80
      name: nginx
    - protocol: TCP  

    - port: 8080
      targetPort: 8080
      name: tomcat
    - protocol: TCP 
  