apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
      ports:
       - containerPort: 80
         protocol: TCP
