apiVersion: v1
kind: Pod
metadata:
  name: sh-pod
spec:
  volumes:
    - name: sh-pod
      persistentVolumeClaim:
        claimName: sh-pv-claim
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: sh-pod
      ports:
       - containerPort: 80
         protocol: TCP
