apiVersion: v1
kind: PersistentVolume
metadata:
  name: sh-pv-volume
  labels:
    type: pv
spec:
  storageClassName: standard 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"
