apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sh-pv-claim
spec:
  storageClassName: standard 
  volumeMode:  Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
