apiVersion: apps/v1
kind:  StatefulSet
metadata: 
  name: statefull
  labels:
    app: configapp
spec:
    selector: 
      matchLabels: 
          app: configapp
    replicas: 10
    template:
      metadata:
        labels:
          name: mdb
          app: configapp
      spec:
        containers:
          - name: mysql
            image: mysql
            ports:
                - containerPort: 3306
                  protocol: TCP
            env:
                 - name: MYSQL_ROOT_PASSWORD
                   valueFrom:
                        configMapKeyRef:
                          name: config
                          key: rootpw
